version: '3.7'

services:
  server:
    env_file:
      - ./api-server/.env
      - ./api-server/.prod.env
      - ./api-server/.secret.env

  db:
    env_file:
      - ./api-server/.prod.env
      - ./api-server/.secret.env

  caddy:
    volumes:
      - type: bind
        source: ./api-server/Caddyfile
        target: /etc/Caddyfile
      - type: bind
        source: ./api-server/app/assets/server.key
        target: /app/server.key
      - type: bind
        source: ./api-server/app/assets/server.crt
        target: /app/server.crt
      - caddypath:/var/caddy
      - sites:/var/www/sites
