version: '3.7'

services:
  frontend:
    build: ./angular
    restart: always
    ports:
      - "80"
    depends_on:
      - server

  server:
    build: ./api-server
    command: /app/script/start
    restart: always
    volumes:
      - bundle:/bundle
    ports:
      - "5000"
    depends_on:
      - db
      - sidekiq

  caddy:
    environment:
      - ACME_AGREE=true
    image: abiosoft/caddy:1.0.3-no-stats
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres:9.6.7-alpine
    ports:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  sidekiq:
    build: ./api-server
    command: bundle exec sidekiq
    env_file:
      - ./api-server/.env
    depends_on:
      - redis

  redis:
    image: redis:5.0.5-alpine3.10

volumes:
  bundle:
  postgres:
  sites:
  caddypath:
