version: '3.7'

services:
  server:
    volumes:
      - type: bind
        source: ./api-server/config/master.key
        target: /app/config/master.key
    env_file:
      - ./api-server/.env
      - ./api-server/.secret.env
      - ./api-server/.prod.env

  db:
    env_file:
      - ./api-server/.prod.env

  caddy:
    volumes:
      - type: bind
        source: ./api-server/Caddyfile-dev
        target: /etc/Caddyfile
      - type: bind
        source: ./api-server/app/assets/server.key
        target: /app/server.key
      - type: bind
        source: ./api-server/app/assets/server.crt
        target: /app/server.crt

  redis:
    ports:
      - "6379:6379"

  node_one:
    build:
      context: ./osqueryd
      dockerfile: ./docker/Dockerfile-node1
    restart: always
    depends_on:
      - caddy
      - server

  node_two:
    build:
      context: ./osqueryd
      dockerfile: ./docker/Dockerfile-node2
    restart: always
    depends_on:
      - caddy
      - server

  node_three:
    build:
      context: ./osqueryd
      dockerfile: ./docker/Dockerfile-node3
    restart: always
    depends_on:
      - caddy
      - server

  #node_four:
    #build:
      #context: ./osqueryd
      #dockerfile: ./docker/Dockerfile-node4
    #restart: always
    #depends_on:
      #- caddy
      #- server

