version: '3.7'

services:
  server:
    build: ./api-server
    command: /app/script/start
    restart: always
    volumes:
      - bundle:/bundle
    ports:
      - "5000"
    links:
      - db

  caddy:
    image: abiosoft/caddy:no-stats
    restart: always
    ports:
      - "443:443"

  db:
    image: postgres:9.6.7-alpine
    ports:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  bundle:
  postgres:
