default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['CYBER_LOCAL_DB_USERNAME'] %>
  password: <%= ENV['CYBER_LOCAL_DB_PASSWORD'] %>

development:
  <<: *default
  database: api_server_development

test:
  <<: *default
  database: api_server_test

production:
  adapter: postgresql
  host: db
  port: 5432
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
