version: '3.7'

services:
  server:
    build: .
    command: ./script/start
    restart: always
    env_file:
      - .env
    volumes:
      - bundle:/bundle
    ports:
      - "5000"
    links:
      - db

  caddy:
    image: abiosoft/caddy
    restart: always
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/Caddyfile
      - type: bind
        source: ./app/assets/server.key
        target: /app/server.key
      - type: bind
        source: ./app/assets/server.crt
        target: /app/server.crt
    ports:
      - "443:443"

  db:
    image: postgres:9.6.7-alpine
    ports:
      - '5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  bundle:
  postgres:
