# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'bcrypt'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rails', '~> 6.0.0.rc1'
gem 'rake', '~> 12.3.3'

gem 'gauntlt'
gem 'jwt', '~> 1.5'
gem 'lograge'
gem 'rswag', '~> 2.0', '>= 2.0.5'

gem 'sidekiq'

# json serialization / marshalling
gem 'jsonapi-rails'
gem 'active_model_serializers', '~> 0.10.9'
gem 'fast_jsonapi'
gem 'oj'

gem 'byebug'

group :development, :test do
  gem 'dotenv-rails'
  gem 'fabrication', '~> 2.20'
  gem 'json-schema', '~> 2.8', '>= 2.8.1'
  gem 'rspec-rails', '~> 3.8'
  gem 'rubocop'
end

group :development do
  gem 'brakeman'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'seed_dump'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
