source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 6.0.0.rc1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'bcrypt'

gem 'lograge'
gem 'gauntlt'
gem 'jwt', '~> 1.5'

gem 'dotenv-rails', groups: [:development, :test]
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development, :test do
  gem 'fabrication', '~> 2.20'
  gem 'rspec-rails', '~> 3.8'
  gem 'json-schema', '~> 2.8', '>= 2.8.1'
end

group :development do
  gem 'seed_dump'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
