name: Cyber

channels:
  - conda-forge

dependencies:
  - pip=19.1.1
  - python=3.6.5
  - pyjwt=1.7.1
  - redis-py=3.2.0
  - celery[redis]=4.1.1
  - psycopg2=2.7.5
  - pip:
    - bcrypt==3.1.4
    - coverage==4.5.1
    - sanic==19.03.1
    - sanic-cors==0.9.5
    - snips-nlu==0.19.7
