- hosts: cyber

  tasks:

    - name: Ping Master
      ping:

    - name: Copy Private SSH Key
      copy:
        src: ../keys/cyber
        dest: /home/ubuntu/.ssh/id_rsa
        owner: ubuntu
        group: ubuntu
        mode: 0400

    - name: Copy Public SSH Key
      copy:
        src: ../keys/cyber.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker Repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: yes

    - name: Add Ruby Repo
      apt_repository:
        repo: ppa:brightbox/ruby-ng
        state: present
      become: yes

    - name: Update Packages
      apt:
        upgrade: yes
        update_cache: yes
      become: yes

    - name: Install Required Packages
      apt:
        name: ['docker-ce', 'ruby2.6', 'ruby2.6-dev']
      become: yes

    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: yes

#    - name: Install Python Pip
#      apt:
#        name: "python3-pip"
#        state: latest
#        update_cache: yes
#      become: yes
#
#    - name: Clone Kubespray
#      git:
#        repo: https://github.com/kubernetes-sigs/kubespray
#        dest: /home/ubuntu/kubespray
#        version: release-2.10
#
#    - name: Enforce Ansible 2.7
#      lineinfile:
#        path: /home/ubuntu/kubespray/requirements.txt
#        regexp: '^ansible>=2.7.8'
#        line: ansible==2.7.10
#
#    - name: Install Kubespray Requirements
#      pip:
#        requirements: requirements.txt
#      args:
#        chdir: "/home/ubuntu/kubespray"
#      become: yes
#
#    - name: Copy Cluster Config File
#      command: "cp -rfp inventory/sample inventory/mycluster"
#      args:
#        chdir: "/home/ubuntu/kubespray"
#
#    - name: Configure Kubespray for AWS
#      lineinfile:
#        path: /home/ubuntu/kubespray/inventory/mycluster/group_vars/all/all.yml
#        regexp: '^# cloud_provider:'
#        line: "cloud_provider: 'aws'"
#
#    - name: Update Kubespray Inventory
#      shell: declare -a IPS=(10.0.0.10 10.0.1.10-10.0.1.12) && CONFIG_FILE=inventory/mycluster/hosts.yml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
#      args:
#        chdir: "/home/ubuntu/kubespray"
#        executable: /bin/bash
#
#    - name: Install Kubernetes
#      shell: ansible-playbook -i inventory/mycluster/hosts.yml --become --become-user=root cluster.yml
#      args:
#        chdir: "/home/ubuntu/kubespray"
