- hosts: node2

  tasks:

    - name: Ping Node2
      ping:

    - name: Download osquery
      get_url:
        url: https://pkg.osquery.io/deb/osquery_3.3.2_1.linux.amd64.deb
        dest: /home/ubuntu
        checksum: sha256:6c54a55df1feaf410064bc87696f9829d0787fb5b9c7beabeb4f5cca7ce6c3fb

    - name: Install a .deb package
      apt:
        deb: /home/ubuntu/osquery_3.3.2_1.linux.amd64.deb
      become: yes

    - name: Copy osquery config file
      copy:
        src: /usr/share/osquery/osquery.example.conf
        dest: /etc/osquery/osquery.conf
        remote_src: yes
      become: yes

    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        insertafter: '127.0.0.1 localhost'
        content: |
          10.0.0.10 cyber.ossys.com