- hosts: node4

  tasks:

    - name: Ping Node4
      win_ping:

    - name: Install osqueryd
      win_chocolatey:
        name: osquery
        state: present

    - name: Copy osquery flags file
      win_copy:
        src: /home/ubuntu/cyber-server/osqueryd/flags/osquery.flags
        dest: C:\Program Files\osquery\osquery.flags

    - name: Copy osquery secret file
      win_copy:
        src: /home/ubuntu/cyber-server/api-server/.secret.tmp
        dest: C:\Program Files\osquery\secret

    - name: Download osquery safe script
      win_get_url:
        url: https://raw.githubusercontent.com/osquery/osquery/master/tools/provision/chocolatey/osquery_utils.ps1
        dest: C:\Program Files\osquery\osquery_utils.ps1

    - name: Source osquery utils script
      win_shell: . C:\Program Files\osquery\osquery_utils.ps1

    - name: Run set safe permissions script
      win_shell: Set-SafePermissions C:\Program Files\osquery\osqueryd\
