- hosts: node2

  tasks:

    - name: Ping Node2
      ping:

    - name: Download osquery
      get_url:
        url: https://pkg.osquery.io/deb/osquery_3.3.2_1.linux.amd64.deb
        dest: /home/ubuntu
        checksum: sha256:6c54a55df1feaf410064bc87696f9829d0787fb5b9c7beabeb4f5cca7ce6c3fb

    - name: Install a .deb package
      apt:
        deb: /home/ubuntu/osquery_3.3.2_1.linux.amd64.deb
      become: yes

    - name: Copy osquery config file
      copy:
        src: /usr/share/osquery/osquery.example.conf
        dest: /etc/osquery/osquery.conf
        remote_src: yes
      become: yes

    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        insertafter: '{{ item.insertafter }}'
        line: '{{ item.line }}'
      with_items:
        - { insertafter: '127.0.0.1 localhost', line: '10.0.0.10 cyber.ossys.com' }
        - { insertafter: '10.0.0.10 cyber.ossys.com', line: '10.0.1.10 node1' }
        - { insertafter: '10.0.1.10 node1', line: '10.0.1.11 node2' }
        - { insertafter: '10.0.1.11 node2', line: '10.0.1.12 node3' }
        - { insertafter: '10.0.1.12 node3', line: '10.0.1.13 node4' }
        - { insertafter: '10.0.1.13 node4', line: '10.0.1.14 node5' }
      become: yes

    - name: Retrieve Master Cert
      shell: echo quit | openssl s_client -showcerts -connect 10.0.0.10:443 -servername cyber.ossys.com > /etc/osquery/cacert
      become: yes
      become_user: root

    - name: Copy osquery flags
      copy:
        src: /home/ubuntu/cyber-server/osqueryd/flags/osquery.flags
        dest: /etc/osquery/osquery.flags
      become: yes
      become_user: root
