- hosts: node1

  tasks:

    - name: Ping Node1
      ping:

    - name: Download osquery
      get_url:
        url: https://pkg.osquery.io/rpm/osquery-3.3.2-1.linux.x86_64.rpm
        dest: /home/ec2-user
        checksum: sha256:c69382f622db68036bb61767f1f456474e86d2ad9bf0e33454b9d5dbb543a37e

    - name: Install osquery
      yum:
        name: /home/ec2-user/osquery-3.3.2-1.linux.x86_64.rpm
        state: present
      become: yes

    - name: Copy osquery config file
      copy:
        src: /usr/share/osquery/osquery.example.conf
        dest: /etc/osquery/osquery.conf
        remote_src: yes
      become: yes

    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        insertafter: '{{ item.insertafter }}'
        line: '{{ item.line }}'
      with_items:
        - { insertafter: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4', line: '10.0.0.10 cyber.ossys.com' }
        - { insertafter: '10.0.0.10 cyber.ossys.com', line: '10.0.1.10 node1' }
        - { insertafter: '10.0.1.10 node1', line: '10.0.1.11 node2' }
        - { insertafter: '10.0.1.11 node2', line: '10.0.1.12 node3' }
        - { insertafter: '10.0.1.12 node3', line: '10.0.1.13 node4' }
        - { insertafter: '10.0.1.13 node4', line: '10.0.1.14 node5' }
      become: yes

    - name: Retrieve Master Cert
      shell: echo quit | openssl s_client -showcerts -connect 10.0.0.10:443 -servername cyber.ossys.com > /etc/osquery/cacert
      become: yes
      become_user: root

#    - name: Copy osquery flags
#      copy:
#        src: /home/ubuntu/cyber-server/osqueryd/flags/osquery.flags
#        dest: /etc/osquery/osquery.flags
#      become: yes
#      become_user: root
#
#    - name: Copy osquery secret
#      copy:
#        dest: /etc/osquery/secret
#        content: |
#          very_secret
#      become: yes
#      become_user: root
#
#    - name: Start osquery service
#      service:
#        name: osqueryd
#        state: started
#        enabled: yes
#      become: yes
