- hosts: node4

  tasks:

    - name: Ping Node4
      win_ping:

    - name: Install osqueryd
      win_chocolatey:
        name: osquery
        state: present

    - name: Copy osquery flags file
      win_copy:
        src: /home/ubuntu/cyber-server/osqueryd/flags/osquery.flags
        dest: C:\Program Files\osquery\osquery.flags

    - name: Copy osquery secret file
      win_copy:
        src: /home/ubuntu/cyber-server/api-server/.secret.tmp
        dest: C:\Program Files\osquery\secret
