- hosts: node3

  tasks:

    - name: Ping Node3
      win_ping:

    - name: Add master as a host
      win_hosts:
        canonical_name: '{{ item.name }}'
        ip_address: '{{ item.ip }}'
        state: present
      with_items:
        - { name: 'master', ip: '10.0.0.10' }
        - { name: 'node1', ip: '10.0.1.10' }
        - { name: 'node2', ip: '10.0.1.11' }
        - { name: 'node3', ip: '10.0.1.12' }
        - { name: 'node4', ip: '10.0.1.13' }
        - { name: 'node5', ip: '10.0.1.14' }

    - name: Change Hostname
      win_hostname:
        name: node3
      register: res

    - name: Ping Master
      win_shell: ping.exe -n 1 master

    - name: Install osqueryd
      win_chocolatey:
        name: osquery
        state: present

    - name: Copy osquery flags file
      win_copy:
        src: /home/ubuntu/cyber-server/osqueryd/flags/osquery-win.flags
        dest: C:\Program Files\osquery\osquery.flags

    - name: Copy osquery secret file
      win_copy:
        src: /home/ubuntu/cyber-server/api-server/.secret.tmp
        dest: C:\Program Files\osquery\secret

    - name: Copy server certificate
      win_copy:
        src: /home/ubuntu/cyber-server/api-server/app/assets/server.crt
        dest: C:\Program Files\osquery\cacert

    - name: Download osquery safe script
      win_get_url:
        url: https://raw.githubusercontent.com/osquery/osquery/master/tools/provision/chocolatey/osquery_utils.ps1
        dest: C:\Program Files\osquery\osquery_utils.ps1

    - name: Source osquery utils script
      win_shell: (. C:\\"Program Files\"\osquery\osquery_utils.ps1) -and (Set-SafePermissions C:\\"Program Files\"\osquery\osqueryd\)
      args:
        chdir: C:\Program Files\osquery

## TMP ##
    - name: Uninstall osqueryd service
      win_shell: C:\\"Program Files\"\osquery\manage-osqueryd.ps1 -uninstall osqueryd
      args:
        chdir: C:\Program Files\osquery
#########

    - name: Check osqueryd service
      win_service:
        name: osqueryd
      register: osqueryd

    - name: Install osqueryd service
      win_shell: C:\\"Program Files\"\osquery\manage-osqueryd.ps1 -install -startupArgs 'C:\Program Files\osquery\osquery.flags'
      args:
        chdir: C:\Program Files\osquery
      when: osqueryd.state is not defined or (osqueryd.state is defined and osqueryd.state == 'absent')

    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: osqueryd
        start_mode: auto
        state: restarted
