- hosts: cyber

  - name: Install Node2
    shell: ansible-playbook --inventory-file=./ansible/hosts -u ubuntu --private-key=./keys/cyber ./ansible/node2.yml
    args:
      chdir: '/home/ubuntu/cyber-server'
