- hosts: cyber

  tasks:

    - name: Install osquery
      shell: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook --inventory-file=/home/ubuntu/cyber-server/ansible/hosts -u {{ item.user }} --private-key=/home/ubuntu/.ssh/id_rsa /home/ubuntu/cyber-server/ansible/{{ item.node }}.yml
      args:
        chdir: '/home/ubuntu/cyber-server'
      with_items:
        - { user: 'ec2-user', node: 'node1' }
        - { user: 'ubuntu', node: 'node2' }
        - { user: 'Administrator', node: 'node3' }
        #- { user: 'Administrator', node: 'node4' }
        #- { user: 'Administrator', node: 'node5' }

    - name: Delete Temp Secret File
      file:
        path: /home/ubuntu/cyber-server/api-server/.secret.tmp
        state: absent
