- hosts: cyber

  tasks:

    - name: Install Node2
      shell: ansible-playbook --inventory-file=./ansible/hosts -u ubuntu --private-key=/home/ubuntu/.ssh/id_rsa ./ansible/node2.yml
      args:
        chdir: '/home/ubuntu/cyber-server'
