- hosts: cyber

  tasks:

    - name: Install osquery
      shell: ansible-playbook --inventory-file=./ansible/hosts -u {{ item.user }} --private-key=/home/ubuntu/.ssh/id_rsa ./ansible/{{ item.node }}.yml
      args:
        chdir: '/home/ubuntu/cyber-server'
      with_items:
        - { user: 'ec2-user', node: 'node1' }
        - { user: 'ubuntu', node: 'node2' }
#        - { user: '' node: 'node3' }
#        - { user: '' node: 'node4' }
#        - { user: '' node: 'node5' }
